### ISSUE TITLE
Make default action when clicking a track configurable

### ISSUE THREAD

**Issue by penorzilla** [pimusicbox/pimusicbox#164]
I'm sure this was an intended feature, that clicking a trackname adds the entire album/artist/playlist (depending on what you are looking at currently).

I had a party last night where people were able to add the songs they wanted to the bottom of the que. Well if you are using a touch screen device, when you swipe up or down to scroll through the search, it will more than likely click a trackname and add the entire album/artist/playlist to the que, without warning or confirmation. This also became a problem as people became more intoxicated and forgot to add song to bottom of que and just clicked the trackname instead.

Not only does it add the entire thing to the que, but it also immediately starts playing the song. This was a huge party fowl and made it unappealing to everyone at the party to use.

It would be nice to be able to change what the on_click does with a trackname.

I love what you've done with MusicBox thus far, it utilizes Spotify and a Que system, which I haven't been able to find anywhere else. I'm not sure if the intention with MusicBox was for party settings, but that is how I would like to use it.

**Comment by jcass77** [comment]
This should probably be logged against the [Mopidy-MusicBox-Webclient](https://github.com/pimusicbox/mopidy-musicbox-webclient) project.

Note that the [Mopidy-Mobile](https://github.com/tkem/mopidy-mobile) web client already supports this feature (Settings -> Look and feel -> Default click action).

**Comment by jcass77** [comment]
I see this has already been done (https://github.com/pimusicbox/mopidy-musicbox-webclient/issues/133)

We can probably close the issue here?
