### ISSUE TITLE
Letters are not displayed correctly

### ISSUE THREAD

**Issue by pixiandreas** [pimusicbox/pimusicbox#187]
The "now playing" song is shown right and and also the spotify playlists
but when i browse the local music it shows wrong

I have try it from several computer with diffrent OS and languages

![screenshot from 2014-12-01 12 42 46](https://cloud.githubusercontent.com/assets/4090221/5245165/3a2915a2-7958-11e4-9936-3e49815d272b.png)

**Comment by pixiandreas** [comment]
I'am running 0.5.0

**Comment by jodal** [comment]
I assume this shows correctly in any MPD client? If so, the issue is in the Mopidy-MusicBox-Webclient.

**Comment by pixiandreas** [comment]
Yes, this a Mopidy-MusicBox-Webclient issue

**Comment by kingosticks** [comment]
Can someone give me some pointers? It's unicode from mopidy, which we set as an element's html like everything else. Which modern browsers understand as far as I know. What am I missing?

**Comment by jodal** [comment]
Browsers are required to default to Windows-1252 encoding, if nothing else is specified. If either the web server (Mopidy/Tornado) adds the proper header or the web page has the proper tag in the `<head>` section, then the browser will use that as encoding instead. Mopidy-MusicBox-Webclient has `<meta charset="utf-8">` in `<head>`, so it should be all good there.

I believe we can close this simply based on it being quite old.

**Comment by jodal** [comment]
It is also possible that this is a Mopidy issue with a file system where a non-UTF-8 encoding has been used. I'm guessing that we've fixed multiple bugs like these since last December.
