### ISSUE TITLE
Improve autoplay functionality

### ISSUE THREAD

**Issue by PiPietje** [pimusicbox/pimusicbox#199]
It was already a problem in the rc2 but un 0.5.1 it is stil not function. When you set the AUTOPLAYWAIT to a vallue below 30 sec the stream (I have only used this function with a radiostream) doesnt start.

The message is: "MusicBoxerror: connection refused"

**Comment by kingosticks** [comment]
It would be nice if we could move to a solution that polls Mopidy until it starts accepting commands and doesn't rely on any specific times.

**Comment by jcass77** [comment]
I've proposed a solution for this in https://github.com/woutervanwijk/Pi-MusicBox/pull/289, which polls the MPD server and starts to play the autoplay track as soon as Mopidy is ready to accept connections, instead of waiting for a fixed duration of time.

**Comment by jcass77** [comment]
This was fixed a long time ago via https://github.com/jcass77/Pi-MusicBox/commit/9df624bc6967416989fec14bb2001ae432490159.
