### ISSUE TITLE
gmusic plugin only always pulls 25 tracks no matter what

### ISSUE THREAD

**Issue by er0sion** [pimusicbox/pimusicbox#206]
Is there a way to get max_radio_tracks to work in 0.5.2? adding it to the settings.ini in the gmusic section does nothing and gmusic always pulls 25 tracks, no matter what it is set to.

**Comment by woutervanwijk** [comment]
MusicBox uses the latest version of mopidy-gmusic, so the value should work. Never tested it though

**Comment by jcass77** [comment]
Closing this old issue due to inactivity - please log over at the mopidy-gmusic repository if anybody is still experiencing any issues with this.
