### ISSUE TITLE
Spotify browsing gives "No tracks found..."

### ISSUE THREAD

**Issue by liftarn** [pimusicbox/pimusicbox#220]
I go in Browsing -> Spotify Browse and select, for instance, Featured playlists. I click on any of them and all I get is "No tracks found..."
The same for top lists, "Genres & Moods" and so on.

**Comment by kingosticks** [comment]
Is this still an issue for you? Is this with default webclient (mopidy-musicbox-webclient) ? Do regular Spotify playlists work?

**Comment by liftarn** [comment]
I'm using Pi MusicBox 0.5.3.
I get no Spotify playlists in the playlist tab.

**Comment by kingosticks** [comment]
So this is a general Spotify issue rather something isolated browsing. Do
you have a Spotify premium account? Are there any errors in the logs at
/var/log/mopidy regarding Spotify login?

**Comment by liftarn** [comment]
It is a premium account. No visible error messages in the web client. Will try to extract a log.
