### ISSUE TITLE
Autoplay google music feeling lucky radio on start

### ISSUE THREAD

**Issue by pascalwhoop** [pimusicbox/pimusicbox#237]
Hey. Would it be possible to implement such functionality? google is relatively good with playing music you recently started listening to and it could be useful to have it start playing instead of a static radio stream or something

**Comment by kingosticks** [comment]
I don't actually use Google music so I don't know what that would entail. If the radio station has a uri it can be played at startup as it is. If you start the station and then go to the streams page there is a button to get the uri for what's currently playing.
