### ISSUE TITLE
Add Mopidy-AlarmClock package

### ISSUE THREAD

**Issue by DavisNT** [pimusicbox/pimusicbox#270]
Package [Mopidy-AlarmClock](https://pypi.python.org/pypi/Mopidy-AlarmClock/) provides alarm clock. :bowtie: :bell: 

Currently the package can be manually set up as described in https://github.com/woutervanwijk/Pi-MusicBox/wiki/Setting-up-Alarm-Clock

Integration requires:
* Adding package [Mopidy-AlarmClock](https://pypi.python.org/pypi/Mopidy-AlarmClock/)
* Adding ability to set timezone via web interface https://github.com/woutervanwijk/mopidy-websettings/issues/8 
* Working NTP package for improved clock synchronization (see https://github.com/woutervanwijk/Pi-MusicBox/wiki/Setting-up-Alarm-Clock for Monit config file)

**Comment by DavisNT** [comment]
Is alarm clock feature welcome in Pi MusicBox?

**Comment by kingosticks** [comment]
I'm really unfamiliar with the particular extension other than what has already been highlighted at https://github.com/mopidy/mopidy/pull/1085#issuecomment-90399101. Don't think we've had any requests for the functionality either so it's not hugely interesting.

**Comment by DavisNT** [comment]
Users interested in this feature, please give your feedback here!

When this feature will be welcome, I will possibly implement it. Meanwhile everybody can manually install alarm clock as described in: https://github.com/woutervanwijk/Pi-MusicBox/wiki/Setting-up-Alarm-Clock

**Comment by michaellunzer** [comment]
@DavisNT I'm very interested! I was able to add your solution as you suggested however it would be nice to see the alarm section completely integrated into @woutervanwijk's pimusicbox frontend (maybe as a new tab
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by DavisNT** [comment]
@kingosticks Is a Pull Request for MusicBox Webclient addling a link to AlarmClock (if it is installed) in main menu welcome?

**Comment by kingosticks** [comment]
I guess it's ok to include a navigation link to it which we'll show only if it's installed (don't want to create another config option for this).

**Comment by michaellunzer** [comment]
I can't wait! Let me know if I can help in any way @DavisNT

**Comment by DavisNT** [comment]
I have created a Pull Request that adds link to Alarm Clock in Musicbox Webclient. 
@michaellunzer thanks for Font Awesome Icon!
@kingosticks could you please do the review and merge?

**Comment by jcass77** [comment]
#104 has been merged which addresses this issue.
