### ISSUE TITLE
Add option to context menu "save to streams"

### ISSUE THREAD

**Issue by joh-klein** [pimusicbox/pimusicbox#278]
It would be very useful (at least during the initial setup phase) to have an option to add search results directly to streams as bookmarks/favorites.

**Comment by kingosticks** [comment]
This feature request belongs in https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/issues but I'm not sure we'll do this. There has to be a limit of how many things we add to the context menu else it gets a bit crowded in here. However, I do see the value in this during initial setup, as you say. It would be nice if it was part of a setup wizard type page.
