### ISSUE TITLE
No advertisement for Mopidy websocket interface 

### ISSUE THREAD

**Issue by kingosticks** [pimusicbox/pimusicbox#291]
We currently disable Mopidy's built-in zeroconf support and advertise all the musicbox services ourselves. In doing so we have omitted the '_mopidy-http._tcp.local' interface which was added later and which is used by some clients (e.g. Mopidy-Mobile) to discover Mopidy's websocket. We need to add this.

**Comment by kingosticks** [comment]
Remotedy also uses this interface.

**Comment by tkem** [comment]
+1 ;-)

**Comment by kingosticks** [comment]
@tkem I was playing around with this and now I can see `_mopidy-http._tcp` in ZeroConf Browser running on my Android phone but mopidy-mobile can't see it (and neither can remotedy). Is there any extra magic it's looking for in the service advert?

**Comment by kingosticks** [comment]
ahh, nevermind, turns out the "service on $host" cannot be "service on $host.local" for some reason. Don't understand why to be honest.

**Comment by tkem** [comment]
@kingosticks: beats me; but MoMo is just using a Cordova ZeroConf plugin, and the inner workings if that are just "magic" to me ;-)
