### ISSUE TITLE
Mopidy deps says not installed, while pip search does.

### ISSUE THREAD

**Issue by Raqbit** [pimusicbox/pimusicbox#336]
I just started using Musicbox, but found out that Youtube isn't working for me. I checked **mopidy debs_, but mopdiy-youtube and others weren't there. Then I executed *_pip search mopidy** and pip showed me that most of them _were_ installed.

Why isn't this working?

**Comment by jodal** [comment]
Can you be more specific and provide exact commands of what you did, what you expected and what happened? For example, what does "checked mopidy debs" mean?

**Comment by PHiAX** [comment]
I've got the same problem, and it literally means running the command **mopidy deps** which outputs the installed plugins

**Comment by kingosticks** [comment]
As of 0.7.0rc4 `mopidy deps` (not debs) works and mopidy-youtube has been upgraded. Whatever problem there was should be no more.
