### ISSUE TITLE
Display hostname and Musicbox version number in title bar

### ISSUE THREAD

**Issue by berrydejager** [pimusicbox/pimusicbox#337]
It would be very handy (i my case at least) to have the hostname and version number shown in the title bar (i.e. 'Home' -> 'Home | LivingRoom (v.0.60)').

Ideally the title bar can have a configurable/customizable syntaxis based on variables. 

$Menu -> 'Home'
$HostName -> musicbox.local
$ProductName -> MusicBox
$ProductVersion -> 0.60
$NowPlayingArtist -> Antony and the Johnsons
$NowPlayingAlbum -> I am a bird now
$NowPlayingSong -> You are my sister
 
The aim is to configure your own header in the GUI.

**Comment by kingosticks** [comment]
This belongs in the webclient repo and sounds like https://github.com/pimusicbox/mopidy-musicbox-webclient/issues/67
