### ISSUE TITLE
shuffle play

### ISSUE THREAD

**Issue by tcurdt** [pimusicbox/pimusicbox#348]
Is there a way to shuffle play a playlist?
I cannot find it.

**Comment by kingosticks** [comment]
Shuffle the playlist s the leftmost icon on the now playing bar. I think it's up and down arrow. Random play is also down there somewhere. They should all have mouse-over descriptions.

**Comment by kingosticks** [comment]
Sorry! I mean right-most icon!

**Comment by tcurdt** [comment]
Found it. Odd. That one is obvious.
I could have sworn I didn't see it on the phone.

**Comment by kingosticks** [comment]
It should be there for all devices, I think it gets a bit squashed down there on small screen devices so we could look at moving them elsewhere. Please create an issue in the webclient repo if you do find a problem on your device.

**Comment by tcurdt** [comment]
Will double check, thanks!
