### ISSUE TITLE
Auto start URL limited to 40 characters

### ISSUE THREAD

**Issue by pengimo** [pimusicbox/pimusicbox#358]
I'm trying to put a URL into the autostart box on the settings page but the input is reducing it to a maximum of 40 characters.

**Comment by jcass77** [comment]
This is actually a mopidy-websettings issue and a duplicate of https://github.com/pimusicbox/mopidy-websettings/issues/3.

It was fixed in v 0.1.4.2 - please update to the latest version by running ``pip install -U mopidy-websettings`` and try again.

**Comment by kingosticks** [comment]
That'll update mopidy too, so don't do that unless you know what you're doing.

**Comment by pengimo** [comment]
Yup. I ran the command and have broken the box :(

**Comment by kingosticks** [comment]
If you can rescue the install (difficult) or are able to reinstall from scratch then next time you can update just the websettings extension with `pip install -I mopidy-websettings==0.1.4.2 `

**Comment by pengimo** [comment]
Thanks @kingosticks. I'll reinstall and give that a try.

**Comment by pengimo** [comment]
Same result. Performed the commands and the box broke again. I think I'll live with the bug for now and just hardcode the auto URL.

**Comment by kingosticks** [comment]
eek sorry. Maybe you must use `-U` instead of `-I`. Basically you don't want to install any of the other dependencies.

**Comment by pengimo** [comment]
Both ways failed and left me with a box that didn't want to work. It booted and the network was fine but the web interface was not accessible. Not to worry.
