### ISSUE TITLE
Is the GPIO connected Cirrus Logic soundcard supported?

### ISSUE THREAD

**Issue by LaKing** [pimusicbox/pimusicbox#359]
Sorry, I couldn't test this yet, but I'm wondering if I need any extra drivers or will it work out of the box?

**Comment by kingosticks** [comment]
From my quick look at the installation instructions for this card I am guessing no, It seems to require a custom kernel rather than a loadable module like most (all?) other raspberry pi audio cards which makes it hard to support for a generic image like this.
