### ISSUE TITLE
HTTP request to toggle Pause / Play

### ISSUE THREAD

**Issue by daviddarke** [pimusicbox/pimusicbox#364]
Is it possible to toggle playback via HTTP request? I recently got hold of a couple of flics https://flic.io/ and there is a HTTP request option out of the box.

I'm assuming that this isn't currently possible?

**Comment by kingosticks** [comment]
For Mopidy: yes see http://mopidy.readthedocs.org/en/release-0.19/api/http/

For airplay: I don't know.

**Comment by daviddarke** [comment]
@kingosticks Thank you so much for your quick response. So polling curl with:
```
curl -d '{"jsonrpc": "2.0", "id": 1, "method": "core.playback.get_state"}' http://musicbox.local:6680/mopidy/rpc
```
works as expected. Yet the UI for the flic is fairly limited:
![photo 12-04-2016 11 35 39](https://cloud.githubusercontent.com/assets/1636310/14457528/02912a3e-00a3-11e6-962f-7ea0d3b44c81.png)
Only allowing for a 'body' field to be sent. I'm assuming they are expecting you to use a REST call.

So I assume this wouldn't work?

**Comment by kingosticks** [comment]
Can't you just post `{"jsonrpc": "2.0", "id": 1, "method": "core.playback.get_state"}` as the body?

**Comment by daviddarke** [comment]
@kingosticks Seems like a limitation their side: http://ideas.flic.io/forums/283403-flic-ideas/suggestions/7178865-http-calls-post-get-and-rest-api-flic-will-bec Thank you for your help!

**Comment by kingosticks** [comment]
Indeed it does, hopefully they will improve.
