### ISSUE TITLE
Add support for JustBoom audio boards

### ISSUE THREAD

**Issue by shawaj** [pimusicbox/pimusicbox#366]
Add support for BoomBerry audio boards. The drivers are supported in kernels 4.1.y and 4.4. y - see files:

sound/soc/bcm/boomberry-dac.c
sound/soc/bcm/boomberry-digi.c
sound/soc/bcm/Kconfig
sound/soc/bcm/Makefile
arch/arm/boot/dts/overlays/boomberry-digi-overlay.dts
arch/arm/boot/dts/overlays/boomberry-dac-overlay.dts
arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/README
arch/arm/configs/bcm2709_defconfig
arch/arm/configs/bcmrpi_defconfig

If you let me know what needs doing in order to support these, happy to do the work and submit a PR :-)

**Comment by kingosticks** [comment]
Sorry for the late reply. I'll include these in the next release.

**Comment by shawaj** [comment]
Just FYI, BoomBerry has had to change name to JustBoom due to a legal challenge over the name. The drivers are in the same place though.

Just out of interest, when will you be doing the next build?

**Comment by shawaj** [comment]
@kingosticks - perhaps we can have a chat over email? We are keen to put one of our software guys on mopidy/musicbox stuff full time and just wanted discuss a few things?

**Comment by shawaj** [comment]
@francesco-vannini FYI here is this issue

**Comment by shawaj** [comment]
@kingosticks thanks - that is awesome!

Is there a RC built including this that we can test already? Or will that come in a few days?

**Comment by kingosticks** [comment]
I'll try and build a new one tonight but it depends how https://github.com/pimusicbox/pimusicbox/issues/370 comes along which is now a blocker for this (as well as Pi3+  Pi0W wifi support). Might be tomorrow / Saturday.

**Comment by shawaj** [comment]
Ok cool. We will wait until next week and get it loaded on our office sound
system for some thorough testing :-)

**Comment by kingosticks** [comment]
Did you guys get a chance to test anything out? I bought a DAC and after having my eardrums nearly blown off (our bug which I keep forgetting about) it sounds good.

**Comment by shawaj** [comment]
@francesco-vannini have you tested this yet?

If not, let's do it tomorrow

**Comment by francesco-vannini** [comment]
I was waiting for a link to an image i could use. Have I missed it?

**Comment by shawaj** [comment]
Yes it's here - https://github.com/pimusicbox/pimusicbox/releases

RC4 :-)

**Comment by francesco-vannini** [comment]
OK, found it and installed it, so far so good!

**Comment by talhoffer** [comment]
I can also confirm it works out of the box for a Pi3 with a JustBoom Digi HAT.

**Comment by kingosticks** [comment]
thanks everyone, I declare it: working!

**Comment by shawaj** [comment]
Awesome - upgrading our office one to this updated software too :-)
