### ISSUE TITLE
MusicBox crashes with incorrect spotify credentials

### ISSUE THREAD

**Issue by vantezzen** [pimusicbox/pimusicbox#367]
Hello,
if you type in wrong creadentials for Spotify (I typed in the wrong password), reboot and then go to Browse > Spotify > Personal... PiMusicBox just crashes and I needed to reboot it manually over the command line.
It be good if it just checks if the credentials are right before it just crashes because of this

**Comment by kingosticks** [comment]
So I'm clear, you are talking about Mopidy failing to start when you put in the wrong credentials, right? Restarting mopidy on the command line should fix it. Unfortunately the web settings frontend is served by mopidy so it cannot be displayed if mopidy isn't running.

**Comment by kingosticks** [comment]
So I'm clear, you are talking about Mopidy failing to start when you put in the wrong credentials, right? Restarting mopidy on the command line should fix it. Unfortunately the web settings frontend is served by mopidy so it cannot be displayed if mopidy isn't running.
