### ISSUE TITLE
Store the Streams URIs on the RPi instead of locally in the browser (cookies)

### ISSUE THREAD

**Issue by SiamKreative** [pimusicbox/pimusicbox#377]
Hi there,

Don't get me wrong, I love the MusicBox! But I think it would be so much better that instead of storing the streams URIs locally in cookies, to store them on the Pi itself. 
### Why?
- Because if you add custom streams from your computer you won't be able to see them on your Android device (and vice versa)
- Because if for some reasons you empty your browser's cache, you'll loose all the custom added streams

Is this possible?

**Comment by kingosticks** [comment]
Hi. In the current version it's not possible but there is an open issue https://github.com/pimusicbox/pimusicbox/issues/352 to support it for the next version. I have closed the other issue in favour of yours since you've explained why this is worth doing.

**Comment by SiamKreative** [comment]
Thanks for the answer. I would be happy to help if you can point in the right direction.

What permanent storage methods are available? How about a local writable JSON file on the SD card?

**Comment by kingosticks** [comment]
Fixed in https://github.com/pimusicbox/pimusicbox/commit/6b7015e44f2d107a86c52db92b421b758e7c0a32

**Comment by SiamKreative** [comment]
Fantastic work, I will give it a try soon :)
