### ISSUE TITLE
Spotify playlists not showing

### ISSUE THREAD

**Issue by rseeg** [pimusicbox/pimusicbox#380]
About one week ago, the webclient no longer shows my list of Spotify playlists.  No other changes were made to the pi musicbox (using V0.6).  The playlists are still visible on Spotify.

I have reimaged the SD card but this has not made any difference.

Thx

**Comment by berrydejager** [comment]
I found a solution for this. However thus workaround needs to have a permanent fix;

[http://virtual.berrydejager.com/pimusicbox-not-showing-spotify-playlist-fixed/](http://virtual.berrydejager.com/pimusicbox-not-showing-spotify-playlist-fixed/)

**Comment by rseeg** [comment]
Thanks for the response.
I managed to fix the issue by removing the cache in the var/cache/mopidy/spotify directory which has been fairly well documented.
