### ISSUE TITLE
Rainbow screen when booting

### ISSUE THREAD

**Issue by habmeister** [pimusicbox/pimusicbox#381]
Hi,

I have installed the 0.6.0 image and whever I boot I see a rainbow screen. It seems it stucks there as it will not show up in IP list in my router. So, it actually does not boot at all.

I am using the newest Raspberry Pi 3 Model B. The hardware is working fine, as I have tested it with a Jessie image.

Is there any setting I can do, or the PiMusicbox is not yet compatible with the Pi 3 Model B?

Thank you in advance.

**Comment by kingosticks** [comment]
Yep, you are correct. Sorry.
