### ISSUE TITLE
ACT light blinks 8 times

### ISSUE THREAD

**Issue by cozyrat** [pimusicbox/pimusicbox#382]
I'm a complete newbie on this. I recently bought a R-Pi model B+ and thought would be cool to get something working on it. I downloaded pimusicbox-0.6.0 and flushed it into the SD card as was instructed. However, the Raspberry Pi didn't seem to connect to the internet even with the Ethernet cable plugged in. The power red light is on. The "act" light is blinking 8 times before a pause. (according to the manual, 8 flashes: 8 flashes: SDRAM not recognised. You need newer bootcode.bin/start.elf firmware.firmware.) The ethernet indicator lights are off.  I used Win32DiskImager to format the SD card (interestingly, I didn't run into issues while flushing Raspbian with it) and I'm pretty sure my wifi adapter works (works with Raspbian). What should I do in this case to fix the problem? Any help is appreciated!

**Comment by kingosticks** [comment]
This was likely due to our old outdated firmware. This has been upgraded to the latest stable version in rc3.
