### ISSUE TITLE
New version of musicbox?

### ISSUE THREAD

**Issue by McKlavishnikov** [pimusicbox/pimusicbox#384]
Hi!
You have made so many cool changes in Mopidy-Musicbox-Webclient that are not available in current build of PiMusicbox so I want to know:
- how can I update pimusicbox 0.6 webclient version to the latest one? I tried to do it via apt-get but I couldn't because it need mopidy version 1.0 or later. I've tried to upgrade mopidy but failed also.
- are you going to release a new version of PiMusicBox that would include all this changes in webclient (and new mopidy version)? If yes, when?

**Comment by kingosticks** [comment]
In regards to upgrading from v0.6, you can try what's described at http://docs.pimusicbox.com/en/develop/upgrading/ but I don't know if it's still working. If you do try, I would suggest skipping step 2.

Yes, for a new version.  Nobody would disagree that it's desperately needed and long overdue. As to when, I don't know. I'm really hoping I can find time to finish off v1.0 before Christmas.
