### ISSUE TITLE
Mopify / Mopidy version is way out of date

### ISSUE THREAD

**Issue by coldfumonkeh** [pimusicbox/pimusicbox#387]
MusicBox is currently running Mopify 1.1.2. As a result, the Spotity Authentication doesnt work (no doubt some other features as well). Upgrading Mopidy / Mopify to the latest version breaks all HTTP servers so nothing is available via the web interface.

Please can you look into updating the used version of Mopidy / Mopify so that it is the current release and HTTP servers remain intact?

Many thanks

**Comment by kingosticks** [comment]
It does work in rc3. An updated mopify was required. Reopen if still a problem.
