### ISSUE TITLE
Pi Zero W Onboard Wifi Won't Work

### ISSUE THREAD

**Issue by cantrollmyrs** [pimusicbox/pimusicbox#393]
Can't seem to find the onboard wifi for a Pi Zero W.

**Comment by kingosticks** [comment]
Unfortunately so. I forgot to add that to the GitHub release notes but have done so now. If anyone can figure it out I'm all ears.

**Comment by kingosticks** [comment]
We need a newer kernel which is blocked by https://github.com/pimusicbox/pimusicbox/issues/370

**Comment by dezeyer** [comment]
I got Wifi working by moving https://raw.githubusercontent.com/RPi-Distro/firmware-nonfree/master/brcm80211/brcm/brcmfmac43430-sdio.txt and https://raw.githubusercontent.com/RPi-Distro/firmware-nonfree/master/brcm80211/brcm/brcmfmac43430-sdio.bin in /lib/firmware/brcm, then reboot.

**Comment by cantrollmyrs** [comment]
@dezeyer how did you move it over?  Can I just open the file via sdcard in my mac and paste the txt content in?

**Comment by cantrollmyrs** [comment]
Nevermind, replaced both files, but still having wifi issues on pi zero w.  Same network error.

**Comment by kingosticks** [comment]
The Solution is coming, need to rebuild the image today, hold on!

**Comment by kingosticks** [comment]
https://github.com/pimusicbox/pimusicbox/releases/tag/v0.7.0RC4
