### ISSUE TITLE
Can you put Pi Music box play songs of videos from Youtube?

### ISSUE THREAD

**Issue by sami10007** [pimusicbox/pimusicbox#396]
[Here](https://www.youtube.com/watch?v=T_Dy9OvgjHY) an example of video for the input.

**Comment by kingosticks** [comment]
Yes. It uses mopidy-youtube, which does exactly this.

**Comment by sami10007** [comment]
How stable is the solution? - - I am thinking how many times has the approach broke because of updates in Youtube.

**Comment by kingosticks** [comment]
It's been solid lately but it's an unofficial API and I can't predict what youtube will do.

**Comment by kingosticks** [comment]
There's no actual issue here so closing. 

If you have any other questions about mopidy-youtube then please direct them at the project directly. 

If you have any other questions about using pimusicbox then please post them at https://discuss.mopidy.com/c/pi-musicbox

**Comment by dhetriteq** [comment]
Youtube is still not working
