### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ryks1** [pimusicbox/pimusicbox#430]
I allways shutdown the pi thru ssh with putty-poweroff command.using for 1year ago without any data or sdcard coruption.
Sometimes when i wanna leasen fast i use moc player installed on pi and thru ssh on my laptop.

**Comment by kingosticks** [comment]
Is there a question or issue here?

**Comment by ryks1** [comment]
Hi

**Comment by ryks1** [comment]
Sorry.first time on github

**Comment by ryks1** [comment]
Was meant to go on coruption data sdcard

**Comment by kingosticks** [comment]
That's OK. The discussion forum is at https://discuss.mopidy.com/c/pi-musicbox
