### ISSUE TITLE
External control

### ISSUE THREAD

**Issue by RogierQ** [pimusicbox/pimusicbox#434]
Is it possible to control start stop from tcp,udp,osc or any other protocol?

**Comment by kingosticks** [comment]
You can control Mopidy playback using JSON-RPC over HTTP using HTTP POST or MPD commands.

**Comment by RogierQ** [comment]
Great! Is there any information about it? Or maybe some examples?

**Comment by kingosticks** [comment]
There's a lot of info and examples online of using MPD. For Mopidy's JSON-RPC, see https://docs.mopidy.com/en/release-1.1/api/http/ (note it's v1.1).

**Comment by kingosticks** [comment]
You'll probably also find more info at https://discuss.mopidy.com/. Since there is no actual issue here can I close this?

**Comment by RogierQ** [comment]
Thanks!
