### ISSUE TITLE
Raspberry Zero W - Bluetooth

### ISSUE THREAD

**Issue by tringler** [pimusicbox/pimusicbox#441]
Hello,

unfortunately I'm unable to use the pi musicbox image with my Raspberry Zero W if I want to use the built-in bluetooth chip.

The bluetooth device is not working (not found at all), because I assume the raspbian image is too old. If I try to update to jessie or stretch the musicbox is not reachable anymore (jessie) or not booting up at all (stretch).

Any ideas how to solve it? Is anyone using a RPiZW with bluetooth successfully?

Thanks in Advance!

**Comment by kingosticks** [comment]
That's a known issue listed in the changelog somewhere. I currently have no fix for that.

**Comment by tringler** [comment]
Ok :( - So I need to attach an BT usb adapter right?

**Comment by kingosticks** [comment]
Yep. Unless you find the solution for wheezy, of course!

**Comment by pierreboissinot** [comment]
Hi, is it fixed now ?

**Comment by kingosticks** [comment]
Sorry, no. There won't be a fix until Musicbox v1.0. Whenever (if ever) that is. It is a little misleading I left this closed, I apologise for that. 

EDIT: In fact, it's because it's already tracked at https://github.com/pimusicbox/pimusicbox/issues/78
