### ISSUE TITLE
TP-Link TL-WN722N is not detecting in Kali linux amd64

### ISSUE THREAD

**Issue by Arun371** [pimusicbox/pimusicbox#442]
![kali](https://user-images.githubusercontent.com/31501221/29974817-c3edc474-8f51-11e7-8bdf-2b15b4ac596a.jpg)

Hi Everyone,

My TP-Link TL-WN722N wifi external adapter is not working on kali linux. 
it is not even listing under lsusb or network settings. Its working fine on HostOS (windows).
I tried all the stuffs like installing backport, uninstalling driver from host, etc.
Please let me know what i am missing here. Attached the screenshot for your reference.
Appreciate your help in advance.

**Comment by kingosticks** [comment]
Please post your problem on a kali Linux forum. This project has nothing at all to do with kali Linux.
