### ISSUE TITLE
Masalah kkarnel tp link tl-wn722n V2.0

### ISSUE THREAD

**Issue by clarksye** [pimusicbox/pimusicbox#451]
i have a problem with tlwn722n v2.0 that i have, so i have installed kernel driver rtl8188EUS_linux_v4.3.0.8_13968.20150417 and rtl8188eu. I installed it in accordance with the directives of README.md, finished installing tlwn722n I can go into (monitor mode) well after that I restart my computer, but my computer fits back up and I try again to go into monitor mode is not (i say WTF! :) "), and i tried removing all drivers about tlwn722n ie: rtl8188EUS_linux_v4.3.0.8_13968.20150417, rtl8188eu and 8188eu.ko on all my computers, and i tried again to install that driver back, but only the driver rtl8188EUS_linux_v4.3.0.8_13968.20150417 which I can install because of which (rtl8188EUS {make error 2 *})
and i try to apt-get update, apt-get upgrade and apt dist-upgrade ,, it turns out my version is up to date! so that's not the case, and (linux header) is the latest one ,, i'm confused and i bucked for (ifconfig wlan0 down, iwconfig wlan0 monitor mode) JREEENG! it turned out to be and I was happy, and I restart my computer again, and I try to monitor mode again and WOW it works! ,, but that's the problem now TP LINK TLWN722n v2.0 I can not stop or switch from WTF monitor mode !,, so I want to ask if it's a problem or not? , THIS THE IMAGE I TAKE
# Helpmeforthis
![kazam_screenshot_00000](https://user-images.githubusercontent.com/26203694/32667619-bc27e9a6-c66d-11e7-809e-788e5659d796.png)
![kazam_screenshot_00001](https://user-images.githubusercontent.com/26203694/32667633-c9646e46-c66d-11e7-97e2-6500ea9a4114.png)
![kazam_screenshot_00002](https://user-images.githubusercontent.com/26203694/32667641-ce4995d0-c66d-11e7-916f-7e84574a5682.png)
![kazam_screenshot_00003](https://user-images.githubusercontent.com/26203694/32667642-d06b41ec-c66d-11e7-99b4-42796bb27ad7.png)
![kazam_screenshot_00004](https://user-images.githubusercontent.com/26203694/32667643-d202dbfa-c66d-11e7-91f1-b4a3db686eed.png)
![kazam_screenshot_00005](https://user-images.githubusercontent.com/26203694/32667645-d34c5d42-c66d-11e7-88b8-7fa7fa8e57a2.png)
![kazam_screenshot_00006](https://user-images.githubusercontent.com/26203694/32667647-d4f2c6c2-c66d-11e7-9bc0-8bc0b02bf266.png)

thankyou ;)

**Comment by clarksye** [comment]
sorry my english is not good ,, that i translated in google translation

**Comment by clarksye** [comment]
makud above is i can not stop from monitor mode ,, but i can still use internet like always, i want to ask if it is problem or not and is this monitor mode working fine or not?

It's all because I deleted all rtl8188eu drivers

**Comment by kingosticks** [comment]
This has nothing to do with pimusicbox. Please find a different place to ask your question.
