### ISSUE TITLE
Remove subsonic support from the feature list

### ISSUE THREAD

**Issue by heylookltsme** [pimusicbox/pimusicbox#466]
I just installed the pi musicbox image and was all pumped to hook it up to my subsonic library, but it wasn't working out of the box. I did some searching and was bummed to find these [two](https://github.com/pimusicbox/pimusicbox/issues/226) [issues](https://github.com/pimusicbox/pimusicbox/issues/349) which seem to indicate that pi musicbox doesn't actually have support for subsonic anymore. 😿 

I propose that subsonic be removed from the feature list in the documentation and website so other poor subsonic users won't get all sad. 

On the other hand, if there are any known workarounds, I am all ears! Thanks 👍

**Comment by kingosticks** [comment]
Sorry about that. I hadn't planned to be on v0.7 for long (and thus unable to use mopidy-subidy) but things worked out a little differently. 

I will remove it from the feature list with the intent of adding it back in the future.

**Comment by heylookltsme** [comment]
Thanks @kingosticks! 👍

**Comment by heylookltsme** [comment]
Also, just for posterity in case someone else comes along hoping for subsonic support, I was able to do without it pretty easily. My subsonic server is running on another raspberry pi that has a hard drive full of my music mounted on it. I just served up that hard drive as a samba share and used pi musicbox's network drive settings to access it. Et viola. ✨
