### ISSUE TITLE
Feature Request: Act as a bluetooth speaker

### ISSUE THREAD

**Issue by flyser** [pimusicbox/pimusicbox#470]
It would be great if pimusicbox could act as a bluetooth speaker. Instructions to set this up can be found on: https://raspberrypi.stackexchange.com/questions/47708/setup-raspberry-pi-3-as-bluetooth-speaker

Use case: I mainly use pimusicbox for spotify connect, but sometimes I would like to use it to play podcasts with the podcast app on my phone.

**Comment by kingosticks** [comment]
Oops, we already have https://github.com/pimusicbox/pimusicbox/issues/78
