### ISSUE TITLE
Unable to locate package qemu-arm-static

### ISSUE THREAD

**Issue by vilomilo** [pimusicbox/pimusicbox#471]
How to install  qemu-arm-static package on ubuntu 16.04?

**Comment by kingosticks** [comment]
I believe the first hits on Google should apply to Ubuntu: https://wiki.debian.org/QemuUserEmulation
Or https://wiki.debian.org/RaspberryPi/qemu-user-static

Depending on exactly what you are doing you may need a more recent version, these can be manually installed from https://github.com/multiarch/qemu-user-static

**Comment by kingosticks** [comment]
Please reopen if this remains an issue for you.
