### ISSUE TITLE
Librespot release v20180322 has double extension

### ISSUE THREAD

**Issue by rinzeb** [pimusicbox/pimusicbox#475]
Just a small heads-up that your [librespot](https://github.com/pimusicbox/librespot/releases/tag/v20180322-aeb205d) release zip has the extension .zip.zip (twice), causing it to be not downloaded in the install script.

**Comment by kingosticks** [comment]
Oh thanks. What a dumb mistake.

**Comment by kingosticks** [comment]
Fixed the release

**Comment by rinzeb** [comment]
No problem. Thanks a lot for all the work you put in pimusicbox!
