### ISSUE TITLE
Run in Machine Box (Virtual Box - Ubuntu)

### ISSUE THREAD

**Issue by raank** [pimusicbox/pimusicbox#478]
Is it possible to run the virtual machine in order to edit the files without the need to always use RaspBerry?

**Comment by kingosticks** [comment]
You can mount both partitions of the image under Linux and edit any file you please. No need for a virtual machine.

**Comment by raank** [comment]
How to edit project before send to SD Card? Like the "Grunt watch server" or **mopidy-mopify**, has possible editing files of src and after generating package to mopidy?

**Comment by kingosticks** [comment]
How does what I said before not enable you to do what you want?

**Comment by raank** [comment]
So you do not have that possibility? :(

**Comment by kingosticks** [comment]
If what I said earlier doesn't help then I guess not.
