### ISSUE TITLE
mopidy-youtube extension problem

### ISSUE THREAD

**Issue by fatino01** [pimusicbox/pimusicbox#482]
hi  i have problem about youtube-extension

![2018-05-30-233854_1364x768_scrot](https://user-images.githubusercontent.com/39773893/40735430-5cef6b8a-6465-11e8-8ebd-48bdc2624920.png)

pls how to fix this problem 

thankyou

**Comment by kingosticks** [comment]
You have this problem with pimusicbox?

**Comment by fatino01** [comment]
@kingosticks 

no but i have problem mopidy 
so i search on internet and i found pimusicbox and this project use mopidy same
and now i can use webui but can't use mopidy-youtube extension

pls help thankyou

**Comment by kingosticks** [comment]
Sure does but that's the point of this project. I think one question is enough.
