### ISSUE TITLE
Airplay crash

### ISSUE THREAD

**Issue by Sytten** [pimusicbox/pimusicbox#490]
There seems to a bug when two devices try to connect to airplay at the same time and than the one pair disconnect, the process seems to crash. Not sure where to get more logs.

**Comment by kingosticks** [comment]
I think this was due to the way we configure shairport-sync to only use 3 ports. I relaxed this in https://github.com/pimusicbox/pimusicbox/releases/tag/v0.7.0RC7 so hopefully this is fixed. Please reopen if not.
