### ISSUE TITLE
Web client not accessible from mobile device

### ISSUE THREAD

**Issue by mrbinr** [pimusicbox/pimusicbox#492]
hi,
I have a strange Pi MusicBox behaviour, when I use address http://musicbox.local from desktop computer  browser it works, but if i try the same address from my phone it cannot reach to  connect to the page.
Both desktop computer and mobile are on same network.

Best Regards
Pascall

**Comment by deeweef** [comment]
Hi Pascall, 
Just had the same problem. In the docs it says that you have to enter the ip-address, but for me just using http://musicbox (without .local) also worked.
Good luck. :)

**Comment by kingosticks** [comment]
Android phones do not understand mDNS .local addresses, it's a joke. If your home router is vaguely decent it should resolve http://musicbox (without .local) just fine. If you are not using an Android phone please re-open this.
