### ISSUE TITLE
upmpdcli apt repository URLs outdated

### ISSUE THREAD

**Issue by almereyda** [pimusicbox/pimusicbox#502]
During update to the latest Raspbian base #324 and also when trying to

    apt-get update
    apt-get dist-upgrade

of a PiMusicBox image, we find that the APT source for `upmpdcli` is not working anymore.

It now uses Let's Encrypt by default. Adding `s` before the colon in the sources in `/etc/sources.list.d/upmpdcli.list`, and installing `apt-transport-https` resolves this for now.

**Comment by kingosticks** [comment]
If you are using apt-cacher-ng (as I do) you will also need to set a `PassThroughPattern` for the domain. There is a good explanation about this [here](https://blog.packagecloud.io/eng/2015/05/05/using-apt-cacher-ng-with-ssl-tls/). I added:
```
PassThroughPattern: .*lesbonscomptes\.com:443.*
```
