### ISSUE TITLE
sec=ntlm not valid for mount.cifs

### ISSUE THREAD

**Issue by djzort** [pimusicbox/pimusicbox#505]
Looks like the option is no longer supported by mount.cifs (version 5.5)

```
root@MusicBox:/opt/musicbox# mount -t cifs -o sec=ntlm,ro,guest //172.29.0.101/tv1/Music /music/Network/
mount error(22): Invalid argument
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
root@MusicBox:/opt/musicbox# mount -t cifs -o ro,guest //172.29.0.101/tv1/Music /music/Network/
root@MusicBox:/opt/musicbox# 

```

editing it out in /opt/musicbox/startup.sh seems to work ok for me

**Comment by kingosticks** [comment]
This will be fixed in the next release: https://github.com/pimusicbox/pimusicbox/commit/832a56a997c8e05f2e2e4fc603f4d4828d981a38

**Comment by djzort** [comment]
Good fix, thanks.

**Comment by kingosticks** [comment]
https://github.com/pimusicbox/pimusicbox/releases/tag/v0.7.0RC7
