### ISSUE TITLE
Audio input

### ISSUE THREAD

**Issue by vilomilo** [pimusicbox/pimusicbox#507]
Hi, here!
I want to ask about pimusicbox software. It's somethink like sonos, example i'm connecting RP 3 to speaker, and wanted to to stream from tv audio by cable to speaker, but control with app. Soo musicbox supporting line in function? or no? because in sonos u can select what want to play.

**Comment by kingosticks** [comment]
No, musicbox doesn't support line in and it's not something I plan to look at. Very few audio HATs have a line in port but of course there are plenty of USB dongles that do. I don't know what it would take to do what you want.
