### ISSUE TITLE
Raspberry POE Hat Support

### ISSUE THREAD

**Issue by agentdeu** [pimusicbox/pimusicbox#509]
Hi,
please update the core image to add support for the Raspberry POE Hat.
Cheers

**Comment by kingosticks** [comment]
Hopefully fixed by https://github.com/pimusicbox/pimusicbox/commit/a19530bfcff8e9662047374694bdfe6575567163 and available in https://github.com/pimusicbox/pimusicbox/releases/tag/v0.7.0RC7. I don't have the hardware so if someone can test this and report back if it's not.
