### ISSUE TITLE
[Request] include htop in musicbox

### ISSUE THREAD

**Issue by m4xcoat** [pimusicbox/pimusicbox#511]

**Comment by kingosticks** [comment]
Isn't this trivial to install with apt-get if you want it? I'm not sure I see the point.

**Comment by m4xcoat** [comment]
sure, but it would be nice if it's pre-installed. just an idea

**Comment by kingosticks** [comment]
OK thanks but I'm usually trying to remove stuff rather than add it. I think we'll stick with people installing it if they want it.
